Repository purescript/purescript, pull requests merged in 2018-04, with the labels that each got.

#3282 [purs ide] Find usages for recursive definitions
  src/Language/PureScript/Ide/Usage.hs
  tests/Language/PureScript/Ide/Test.hs
  tests/Language/PureScript/Ide/UsageSpec.hs
  tests/support/pscide/src/FindUsage/Recursive.purs
Labels: psc-ide

#3290 Add a Makefile with ghcid and testing commands
  Makefile
  package.yaml
  tests/TestHierarchy.hs
  tests/TestIde.hs
  tests/TestPrimDocs.hs
  tests/TestPscPublish.hs
Labels: ready for review

#3299 Raise warning for re-export of qualified module with implicit imports
  examples/warning/ImplicitQualifiedImportReExport.purs
  src/Language/PureScript/AST/Declarations.hs
  src/Language/PureScript/Errors.hs
  src/Language/PureScript/Linter/Imports.hs
Labels: ready for review

#3301 Update `Effect` inlining
  src/Language/PureScript/Constants.hs
  src/Language/PureScript/CoreImp/Optimizer/Inliner.hs
Labels: ready for review

#3298 Switch to Doc for custom type errors & remove TypeConcat/TypeString
  examples/docs/src/TypeLevelString.purs
  examples/failing/2567.purs
  examples/failing/ProgrammableTypeErrors.purs
  examples/failing/ProgrammableTypeErrorsTypeString.purs
  examples/passing/2663.purs
  examples/warning/CustomWarning.purs
  examples/warning/CustomWarning2.purs
  examples/warning/CustomWarning3.purs
  src/Language/PureScript/Constants.hs
  src/Language/PureScript/Docs/Prim.hs
  src/Language/PureScript/Environment.hs
  src/Language/PureScript/Errors.hs
  src/Language/PureScript/Kinds.hs
  tests/support/bower.json
Labels: ready for review

#3129 Check that instance declarations don't overlap
  examples/failing/OverlapAcrossModules.purs
  examples/failing/OverlapAcrossModules/Class.purs
  examples/failing/OverlapAcrossModules/X.purs
  examples/passing/ExportedInstanceDeclarations.purs
  examples/passing/MPTCs.purs
  src/Language/PureScript/TypeChecker.hs
  src/Language/PureScript/TypeChecker/Monad.hs
  tests/support/bower.json
Labels: ready for review

#3305 Add Prim.Row.Lacks constraint
  examples/failing/RowLacks.purs
  examples/passing/RowLacks.purs
  src/Language/PureScript/Constants.hs
  src/Language/PureScript/Docs/Prim.hs
  src/Language/PureScript/Environment.hs
  src/Language/PureScript/TypeChecker/Entailment.hs
  tests/TestPrimDocs.hs
Labels: ready for review

#3311 Add missing output directory to error
  CONTRIBUTORS.md
  src/Language/PureScript/Ide.hs
Labels: ready for review

#3249 Improve parse error messages for .purs-repl
  app/Command/REPL.hs
  src/Language/PureScript/Interactive/Parser.hs
Labels: ready for review

#3309 Remove inlining for `mod` for `Int`
  src/Language/PureScript/CoreImp/Optimizer/Inliner.hs
Labels: ready for review

#3315 Add real error messages for associativity errors
  examples/failing/MixedAssociativityError.purs
  examples/failing/NonAssociativeError.purs
  src/Language/PureScript/AST/Declarations.hs
  src/Language/PureScript/Errors.hs
  src/Language/PureScript/Names.hs
  src/Language/PureScript/Sugar/Operators.hs
  src/Language/PureScript/Sugar/Operators/Binders.hs
  src/Language/PureScript/Sugar/Operators/Common.hs
  src/Language/PureScript/Sugar/Operators/Expr.hs
  src/Language/PureScript/Sugar/Operators/Types.hs
Labels: ready for review

#3278 Fix errors in binding groups missing source spans
  examples/failing/3275-BindingGroupErrorPos.purs
  examples/failing/3275-DataBindingGroupErrorPos.purs
  src/Language/PureScript/TypeChecker.hs
Labels: needs more work

#3324 Introduce `--codegen` argument so targets can be specified explicitly
  CONTRIBUTORS.md
  app/Command/Compile.hs
  src/Language/PureScript/CodeGen/JS.hs
  src/Language/PureScript/Make/Actions.hs
  src/Language/PureScript/Options.hs
Labels: ready for review

#3334 Add evidence for solving empty type classes & keep track of sub goals
  src/Language/PureScript/TypeChecker/Entailment.hs
  tests/purs/failing/LacksWithSubGoal.purs
Labels: ready for review

#3337 Ensure associativity error in type operators doesn't crash
  src/Language/PureScript/Sugar/Operators.hs
  src/Language/PureScript/Sugar/Operators/Types.hs
  tests/purs/failing/3335-TypeOpAssociativityError.purs
Labels: ready for review
